  version: '3'
  services:
    node1:
      build: ./app
      ports:
        - "5001:3000"
    node2:
      build: ./app
      ports:
        - "5002:3000"
    node3:
      build: ./app
      ports:
        - "5003:3000"
  
    nginx:
      build: ./loadbalancer
      ports:
        - "80:80"
      depends_on:
        - node1
        - node2
        - node3